s= "welcome to my world"
print(s.capitalize())
print(s.center(40,"*"))
print(s.count("o",7,len(s)))
print(s.endswith("yfg"))
print(s.endswith("orld"))
print(s.startswith("wel"))
print(s.rfind("e"))
print(s.find("e"))
print(s.index("m"))
print(s.isalnum())
print(s.isalpha())
print(s.rjust(30,'*'))
print(s.upper())
print(s.lower())
print(s.replace("world","company"))
print(s.split(" "))
print(s.swapcase())
print(s.zfill(40))